# Generated by Django 4.0.4 on 2022-05-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('image', models.ImageField(upload_to='prize/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.CreateModel(
            name='PrizeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_requests', to='prize.prize', verbose_name='Приз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на получение приза',
                'verbose_name_plural': 'Заявки на получение приза',
            },
        ),
    ]
