# Generated by Django 4.0.4 on 2022-05-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0003_alter_prizerequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizerequest',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость приза на момент принятия заявки'),
        ),
        migrations.AlterField(
            model_name='prizerequest',
            name='state',
            field=models.CharField(choices=[('Новая', 'New'), ('Отклонена', 'Rejected'), ('В работе', 'Processing'), ('Выполнена', 'Done')], default='Новая', max_length=50, verbose_name='Статус'),
        ),
    ]
