# Generated by Django 4.0.4 on 2022-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0004_alter_prizerequest_cost_alter_prizerequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizerequest',
            name='state',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Отклонена', 'Отклонена'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена')], default='Новая', max_length=50, verbose_name='Статус'),
        ),
    ]
