# Generated by Django 4.0.6 on 2022-08-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0005_alter_prizerequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='time_of_action',
            field=models.DurationField(blank=True, null=True, verbose_name='Время действия'),
        ),
        migrations.AddField(
            model_name='prizerequest',
            name='active_up_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активен до'),
        ),
    ]
