# Generated by Django 4.0.6 on 2022-08-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0006_prize_time_of_action_prizerequest_active_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prize/images', verbose_name='Изображение'),
        ),
    ]
