# Generated by Django 4.0.4 on 2022-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisement_images', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('cost', models.FloatField(default=1.0, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Рекламное объявление',
                'verbose_name_plural': 'Рекламные объявления',
            },
        ),
    ]
