# Generated by Django 4.0.4 on 2022-05-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0002_alter_advertisement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisements', models.ManyToManyField(blank=True, null=True, related_name='viewed_ads', to='advertisement.advertisement', verbose_name='Рекламные объявления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_ads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотренные рекламные объявления',
                'verbose_name_plural': 'Просмотренные рекламные объявления',
            },
        ),
    ]
