# Generated by Django 4.0.4 on 2022-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_viewedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedad',
            name='advertisements',
            field=models.ManyToManyField(blank=True, related_name='viewed_ads', to='advertisement.advertisement', verbose_name='Рекламные объявления'),
        ),
    ]
